"""empty message

Revision ID: 20140a07e2d7
Revises: 65b558441569
Create Date: 2021-08-27 10:28:12.365854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20140a07e2d7'
down_revision = '65b558441569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
